# Generated by Django 4.0.4 on 2022-05-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='project name', max_length=150)),
                ('date', models.DateField(auto_now_add=True, help_text='Date the Prject .')),
                ('completion_time', models.DateField(help_text='Completion time.', verbose_name=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title', max_length=150)),
                ('description', models.TextField(help_text='Description')),
                ('time_estimate', models.IntegerField(help_text='Time')),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
