# Generated by Django 4.0.4 on 2022-05-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the project', max_length=100)),
                ('creation_time', models.DateField(auto_now_add=True, help_text='The project creation time')),
                ('completion_time', models.DateTimeField(help_text='The project completion time', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of a task', max_length=100)),
                ('description', models.TextField(help_text='The task description')),
                ('time_estimate', models.IntegerField(help_text='Task time estimate')),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
